import java.io.*;
import java.nio.file.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class DataBackupService {
    
    // Create a database backup
    public boolean createDatabaseBackup() throws Exception {
        Connection connection = null;
        try {
            // Create backup directory if it doesn't exist
            File backupDir = new File("backups");
            if (!backupDir.exists()) {
                backupDir.mkdirs();
            }
            
            // Generate backup filename
            SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd_HHmmss");
            String timestamp = sdf.format(new Date());
            String backupFileName = "backup_" + timestamp + ".sql";
            String backupFilePath = "backups/" + backupFileName;
            
            connection = DatabaseConnection.getConnection();
            
            try (PrintWriter writer = new PrintWriter(new FileWriter(backupFilePath))) {
                writer.println("-- Barangay Census System Database Backup");
                writer.println("-- Generated on: " + new Date());
                writer.println("-- Generated by: " + CurrentUser.getFullName());
                writer.println();
                
                // Get all tables
                DatabaseMetaData metaData = connection.getMetaData();
                ResultSet tables = metaData.getTables(null, null, "%", new String[]{"TABLE"});
                List<String> tableNames = new ArrayList<>();
                
                while (tables.next()) {
                    String tableName = tables.getString("TABLE_NAME");
                    if (!tableName.toLowerCase().startsWith("sys") && 
                        !tableName.toLowerCase().contains("information_schema")) {
                        tableNames.add(tableName);
                    }
                }
                tables.close();
                
                // Write CREATE TABLE statements and data
                for (String tableName : tableNames) {
                    writer.println("-- Table: " + tableName);
                    writer.println();
                    
                    // Drop table if exists
                    writer.println("DROP TABLE IF EXISTS `" + tableName + "`;");
                    writer.println();
                    
                    // Get create table statement
                    ResultSet createTableRS = connection.createStatement().executeQuery(
                        "SHOW CREATE TABLE `" + tableName + "`");
                    if (createTableRS.next()) {
                        writer.println(createTableRS.getString(2) + ";");
                    }
                    createTableRS.close();
                    writer.println();
                    
                    // Get table data
                    ResultSet dataRS = connection.createStatement().executeQuery(
                        "SELECT * FROM `" + tableName + "`");
                    ResultSetMetaData rsmd = dataRS.getMetaData();
                    int columnCount = rsmd.getColumnCount();
                    
                    while (dataRS.next()) {
                        StringBuilder insertQuery = new StringBuilder();
                        insertQuery.append("INSERT INTO `").append(tableName).append("` VALUES (");
                        
                        for (int i = 1; i <= columnCount; i++) {
                            Object value = dataRS.getObject(i);
                            
                            if (value == null) {
                                insertQuery.append("NULL");
                            } else {
                                String stringValue = value.toString();
                                // Escape special characters
                                stringValue = stringValue.replace("'", "''");
                                stringValue = stringValue.replace("\\", "\\\\");
                                
                                if (value instanceof Number) {
                                    insertQuery.append(stringValue);
                                } else {
                                    insertQuery.append("'").append(stringValue).append("'");
                                }
                            }
                            
                            if (i < columnCount) {
                                insertQuery.append(", ");
                            }
                        }
                        insertQuery.append(");");
                        writer.println(insertQuery.toString());
                    }
                    writer.println();
                    dataRS.close();
                }
                
                writer.println("-- Backup completed successfully");
                System.out.println("Backup created: " + backupFilePath);
                return true;
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            throw new Exception("Failed to create backup: " + e.getMessage());
        } finally {
            if (connection != null) {
                try {
                    connection.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }
    
    // Restore database from backup file
    public boolean restoreDatabase(File backupFile) throws Exception {
        Connection connection = null;
        Statement statement = null;
        
        try {
            connection = DatabaseConnection.getConnection();
            statement = connection.createStatement();
            
            // Read backup file
            List<String> sqlCommands = readSQLFile(backupFile);
            
            // Execute SQL commands
            for (String sql : sqlCommands) {
                String trimmed = sql.trim();
                if (!trimmed.isEmpty() && !trimmed.startsWith("--")) {
                    try {
                        statement.execute(sql);
                    } catch (SQLException e) {
                        System.err.println("Error executing: " + sql.substring(0, Math.min(50, sql.length())) + "...");
                        System.err.println("Error: " + e.getMessage());
                        // Continue with next command
                    }
                }
            }
            
            return true;
            
        } catch (Exception e) {
            throw new Exception("Failed to restore database: " + e.getMessage());
        } finally {
            if (statement != null) {
                try {
                    statement.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            if (connection != null) {
                try {
                    connection.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }
    
    // Read SQL file and split into commands
    private List<String> readSQLFile(File file) throws IOException {
        List<String> commands = new ArrayList<>();
        StringBuilder currentCommand = new StringBuilder();
        
        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = reader.readLine()) != null) {
                // Skip comments
                if (line.trim().startsWith("--")) {
                    continue;
                }
                
                currentCommand.append(line);
                
                // Check if line ends with semicolon
                if (line.trim().endsWith(";")) {
                    commands.add(currentCommand.toString());
                    currentCommand = new StringBuilder();
                } else {
                    currentCommand.append(" ");
                }
            }
            
            // Add any remaining command
            if (currentCommand.length() > 0) {
                commands.add(currentCommand.toString());
            }
        }
        
        return commands;
    }
    
    // Export data to various formats
    public boolean exportData(File exportFile, String format, 
                            boolean includeHouseholds, boolean includeMembers,
                            boolean includeUsers, boolean includeReports) throws Exception {
        
        try {
            switch (format) {
                case "CSV":
                    return exportToCSV(exportFile, includeHouseholds, includeMembers, includeUsers, includeReports);
                case "Excel":
                    return exportToExcel(exportFile, includeHouseholds, includeMembers, includeUsers, includeReports);
                case "PDF":
                    return exportToPDF(exportFile, includeHouseholds, includeMembers, includeUsers, includeReports);
                case "JSON":
                    return exportToJSON(exportFile, includeHouseholds, includeMembers, includeUsers, includeReports);
                default:
                    throw new Exception("Unsupported export format: " + format);
            }
        } catch (Exception e) {
            throw new Exception("Export failed: " + e.getMessage());
        }
    }
    
    // Export to CSV
    private boolean exportToCSV(File exportFile, boolean includeHouseholds, boolean includeMembers,
                              boolean includeUsers, boolean includeReports) throws Exception {
        
        try (PrintWriter writer = new PrintWriter(new FileWriter(exportFile))) {
            // Write header
            writer.println("Barangay Census System - Data Export");
            writer.println("Export Date: " + new Date());
            writer.println("Exported By: " + CurrentUser.getFullName());
            writer.println();
            
            Connection connection = DatabaseConnection.getConnection();
            
            if (includeHouseholds) {
                writer.println("HOUSEHOLD DATA");
                writer.println("==============");
                exportTableToCSV(writer, connection, "households");
                writer.println();
            }
            
            if (includeMembers) {
                writer.println("HOUSEHOLD MEMBER DATA");
                writer.println("====================");
                exportTableToCSV(writer, connection, "household_members");
                writer.println();
            }
            
            if (includeUsers) {
                writer.println("USER DATA");
                writer.println("=========");
                exportTableToCSV(writer, connection, "users");
                writer.println();
            }
            
            if (includeReports) {
                writer.println("REPORT DATA");
                writer.println("===========");
                exportTableToCSV(writer, connection, "reports");
                writer.println();
            }
            
            connection.close();
            return true;
            
        } catch (Exception e) {
            throw new Exception("CSV export failed: " + e.getMessage());
        }
    }
    
    // Export single table to CSV
    private void exportTableToCSV(PrintWriter writer, Connection connection, String tableName) 
            throws SQLException {
        
        Statement statement = connection.createStatement();
        ResultSet rs = statement.executeQuery("SELECT * FROM " + tableName);
        ResultSetMetaData metaData = rs.getMetaData();
        int columnCount = metaData.getColumnCount();
        
        // Write column headers
        for (int i = 1; i <= columnCount; i++) {
            writer.print("\"" + metaData.getColumnName(i) + "\"");
            if (i < columnCount) writer.print(",");
        }
        writer.println();
        
        // Write data
        while (rs.next()) {
            for (int i = 1; i <= columnCount; i++) {
                Object value = rs.getObject(i);
                if (value != null) {
                    String strValue = value.toString();
                    // Escape quotes
                    strValue = strValue.replace("\"", "\"\"");
                    writer.print("\"" + strValue + "\"");
                } else {
                    writer.print("\"\"");
                }
                if (i < columnCount) writer.print(",");
            }
            writer.println();
        }
        
        rs.close();
        statement.close();
    }
    
    // Export to Excel (simple CSV format that can be opened in Excel)
    private boolean exportToExcel(File exportFile, boolean includeHouseholds, boolean includeMembers,
                                boolean includeUsers, boolean includeReports) throws Exception {
        
        // For simplicity, we'll create a CSV that Excel can open
        String csvFilePath = exportFile.getAbsolutePath();
        if (!csvFilePath.toLowerCase().endsWith(".xlsx") && !csvFilePath.toLowerCase().endsWith(".xls")) {
            csvFilePath = csvFilePath + ".xlsx";
            exportFile = new File(csvFilePath);
        }
        
        // Create CSV content
        return exportToCSV(exportFile, includeHouseholds, includeMembers, includeUsers, includeReports);
    }
    
    // Export to PDF (simple text file for now)
    private boolean exportToPDF(File exportFile, boolean includeHouseholds, boolean includeMembers,
                              boolean includeUsers, boolean includeReports) throws Exception {
        
        // Create a simple text file that can be printed
        try (PrintWriter writer = new PrintWriter(new FileWriter(exportFile))) {
            writer.println("PDF Export - Barangay Census System");
            writer.println("====================================");
            writer.println();
            writer.println("Export Date: " + new Date());
            writer.println("Exported By: " + CurrentUser.getFullName());
            writer.println();
            
            Connection connection = DatabaseConnection.getConnection();
            
            if (includeHouseholds) {
                writer.println("HOUSEHOLD DATA");
                writer.println("==============");
                writer.println();
                exportTableToText(writer, connection, "households");
            }
            
            if (includeMembers) {
                writer.println();
                writer.println("HOUSEHOLD MEMBER DATA");
                writer.println("====================");
                writer.println();
                exportTableToText(writer, connection, "household_members");
            }
            
            if (includeUsers) {
                writer.println();
                writer.println("USER DATA");
                writer.println("=========");
                writer.println();
                exportTableToText(writer, connection, "users");
            }
            
            if (includeReports) {
                writer.println();
                writer.println("REPORT DATA");
                writer.println("===========");
                writer.println();
                exportTableToText(writer, connection, "reports");
            }
            
            connection.close();
            return true;
            
        } catch (Exception e) {
            throw new Exception("PDF export is not fully implemented. Use CSV or Excel instead.");
        }
    }
    
    // Export table to text format
    private void exportTableToText(PrintWriter writer, Connection connection, String tableName) 
            throws SQLException {
        
        Statement statement = connection.createStatement();
        ResultSet rs = statement.executeQuery("SELECT * FROM " + tableName);
        ResultSetMetaData metaData = rs.getMetaData();
        int columnCount = metaData.getColumnCount();
        
        // Write column headers
        for (int i = 1; i <= columnCount; i++) {
            writer.print(String.format("%-20s", metaData.getColumnName(i)));
        }
        writer.println();
        
        // Write separator
        for (int i = 1; i <= columnCount; i++) {
            writer.print("--------------------");
        }
        writer.println();
        
        // Write data
        while (rs.next()) {
            for (int i = 1; i <= columnCount; i++) {
                Object value = rs.getObject(i);
                String strValue = value != null ? value.toString() : "";
                if (strValue.length() > 18) {
                    strValue = strValue.substring(0, 15) + "...";
                }
                writer.print(String.format("%-20s", strValue));
            }
            writer.println();
        }
        
        rs.close();
        statement.close();
    }
    
    // Export to JSON
    private boolean exportToJSON(File exportFile, boolean includeHouseholds, boolean includeMembers,
                               boolean includeUsers, boolean includeReports) throws Exception {
        
        try (PrintWriter writer = new PrintWriter(new FileWriter(exportFile))) {
            writer.println("{");
            writer.println("  \"export\": {");
            writer.println("    \"system\": \"Barangay Census System\",");
            writer.println("    \"date\": \"" + new Date() + "\",");
            writer.println("    \"exported_by\": \"" + CurrentUser.getFullName() + "\",");
            
            Connection connection = DatabaseConnection.getConnection();
            
            if (includeHouseholds) {
                writer.println("    \"households\": [");
                exportTableToJSON(writer, connection, "households", includeMembers || includeUsers || includeReports);
                writer.println("    ],");
            }
            
            if (includeMembers) {
                writer.println("    \"household_members\": [");
                exportTableToJSON(writer, connection, "household_members", includeUsers || includeReports);
                writer.println("    ],");
            }
            
            if (includeUsers) {
                writer.println("    \"users\": [");
                exportTableToJSON(writer, connection, "users", includeReports);
                writer.println("    ],");
            }
            
            if (includeReports) {
                writer.println("    \"reports\": [");
                exportTableToJSON(writer, connection, "reports", false);
                writer.println("    ]");
            } else if (includeHouseholds || includeMembers || includeUsers) {
                // Remove last comma if no reports
                writer.println("    \"reports\": []");
            }
            
            connection.close();
            
            writer.println("  }");
            writer.println("}");
            
            return true;
            
        } catch (Exception e) {
            throw new Exception("JSON export failed: " + e.getMessage());
        }
    }
    
    // Export table to JSON format
    private void exportTableToJSON(PrintWriter writer, Connection connection, 
                                  String tableName, boolean addComma) throws SQLException {
        
        Statement statement = connection.createStatement();
        ResultSet rs = statement.executeQuery("SELECT * FROM " + tableName);
        ResultSetMetaData metaData = rs.getMetaData();
        int columnCount = metaData.getColumnCount();
        
        boolean firstRow = true;
        while (rs.next()) {
            if (!firstRow) {
                writer.println("      ,");
            }
            firstRow = false;
            
            writer.println("      {");
            for (int i = 1; i <= columnCount; i++) {
                String columnName = metaData.getColumnName(i);
                Object value = rs.getObject(i);
                
                writer.print("        \"" + columnName + "\": ");
                
                if (value == null) {
                    writer.print("null");
                } else if (value instanceof Number) {
                    writer.print(value);
                } else {
                    // Escape special JSON characters
                    String strValue = value.toString()
                        .replace("\\", "\\\\")
                        .replace("\"", "\\\"")
                        .replace("\n", "\\n")
                        .replace("\r", "\\r")
                        .replace("\t", "\\t");
                    writer.print("\"" + strValue + "\"");
                }
                
                if (i < columnCount) {
                    writer.println(",");
                } else {
                    writer.println();
                }
            }
            writer.print("      }");
        }
        
        if (firstRow) {
            writer.println();
        } else {
            writer.println();
        }
        
        rs.close();
        statement.close();
    }
    
    // Import data from file
    public int importData(File importFile, String importType) throws Exception {
        // For now, this is a simplified implementation
        // In a real application, you would parse the file based on its format
        
        String fileName = importFile.getName().toLowerCase();
        
        if (fileName.endsWith(".csv")) {
            return importFromCSV(importFile, importType);
        } else if (fileName.endsWith(".json")) {
            return importFromJSON(importFile, importType);
        } else {
            throw new Exception("Unsupported file format. Please use CSV or JSON.");
        }
    }
    
    // Import from CSV
    private int importFromCSV(File importFile, String importType) throws Exception {
        // Simplified CSV import - in real app, parse properly
        int count = 0;
        
        try (BufferedReader reader = new BufferedReader(new FileReader(importFile))) {
            String line;
            boolean isFirstLine = true;
            List<String> headers = new ArrayList<>();
            
            while ((line = reader.readLine()) != null) {
                if (line.trim().isEmpty() || line.startsWith("#")) {
                    continue;
                }
                
                if (isFirstLine) {
                    // Parse headers
                    String[] headerArray = line.split(",");
                    for (String header : headerArray) {
                        headers.add(header.trim().replace("\"", ""));
                    }
                    isFirstLine = false;
                    continue;
                }
                
                // Parse data line
                String[] values = line.split(",(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)");
                if (values.length == headers.size()) {
                    // Here you would insert into database
                    // For now, just count
                    count++;
                }
            }
        }
        
        return count;
    }
    
    // Import from JSON
    private int importFromJSON(File importFile, String importType) throws Exception {
        // Simplified JSON import
        int count = 0;
        
        try (BufferedReader reader = new BufferedReader(new FileReader(importFile))) {
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.contains("\"households\":") || 
                    line.contains("\"household_members\":") || 
                    line.contains("\"users\":") ||
                    line.contains("\"reports\":")) {
                    // Count objects
                    count++;
                }
            }
        }
        
        return count;
    }
    
    // Get last backup path
    public String getLastBackupPath() {
        File backupDir = new File("backups");
        if (!backupDir.exists()) {
            return "No backups found";
        }
        
        File[] backupFiles = backupDir.listFiles((dir, name) -> name.endsWith(".sql"));
        if (backupFiles == null || backupFiles.length == 0) {
            return "No backups found";
        }
        
        // Get most recent backup
        File lastBackup = backupFiles[0];
        for (File file : backupFiles) {
            if (file.lastModified() > lastBackup.lastModified()) {
                lastBackup = file;
            }
        }
        
        return lastBackup.getAbsolutePath();
    }
    
    // Get list of available backups
    public List<String> getAvailableBackups() {
        List<String> backups = new ArrayList<>();
        File backupDir = new File("backups");
        
        if (backupDir.exists()) {
            File[] backupFiles = backupDir.listFiles((dir, name) -> name.endsWith(".sql"));
            if (backupFiles != null) {
                for (File file : backupFiles) {
                    backups.add(file.getName() + " - " + 
                               new SimpleDateFormat("yyyy-MM-dd HH:mm").format(
                                   new Date(file.lastModified())));
                }
            }
        }
        
        return backups;
    }
}